
pipeline {

  agent any

  environment {
    BRANCH   = 'main'
    REPO_URL = 'https://github.com/PraveenKuberABC/Amazon-Jenkins'
    POM_PATH = 'Amazon/Amazon-Core/pom.xml'
  }

  stages {

    stage('Clone') {
      steps {
        git branch: "${BRANCH}",
        url: "${REPO_URL}"
      }
    }

    stage('Build') {
      steps {
        sh "mvn clean install -f ${POM_PATH}"
      }
    }
  }
}
