
pipeline {
    agent any
    environment {
        BRANCH   = 'main'
        REPO_URL = 'https://github.com/Gousia20/Amazon.git'
    }
    stages {
        stage('Clone') { 
            steps {
                git branch: "${BRANCH}",
                    url: "${REPO_URL}"
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
    }
    post {
        success {
            emailext subject: 'Build Success',
                     body: 'Build passed successfully!',   
                     to: 'gousia13batch@gmail.com'
        }
        failure {
            emailext subject: 'Build Failed',
                     body: 'Build has failed!',
                     to: 'gousia13batch@gmail.com'
        }
    }
}
