pipeline {
  agent any 
  stages {

    stage('checkout') {
      steps{
      git branch: 'master' , url: 'https://github.com/Gousia20/Amazon.git'
      }
    }

    stage('build') {
      steps {
        echo "build has started"
        sh 'mvn compile'
      }
    }

    stage('unit test') {
    steps {
      echo "running unit test"
      sh 'mvn test'
    }
  }

  stage('package') {
  steps {
    echo "packaging the artifacts"
    sh 'mvn package'
  }
}
}
  
post {
  success {
    echo "build was successfull"
  }
  failure {
    echo "build failed"
  }
}
}


